// flow-typed signature: 83ca2c35861eb6b6131aff6e498ecd7c
// flow-typed version: <<STUB>>/form-urlencoded_v^2.0.4/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'form-urlencoded'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'form-urlencoded' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'form-urlencoded/dist/form-urlencoded' {
  declare module.exports: any;
}

declare module 'form-urlencoded/form-urlencoded' {
  declare module.exports: any;
}

declare module 'form-urlencoded/spec/form-urlencoded.spec' {
  declare module.exports: any;
}

declare module 'form-urlencoded/spec/helpers/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'form-urlencoded/dist/form-urlencoded.js' {
  declare module.exports: $Exports<'form-urlencoded/dist/form-urlencoded'>;
}
declare module 'form-urlencoded/form-urlencoded.js' {
  declare module.exports: $Exports<'form-urlencoded/form-urlencoded'>;
}
declare module 'form-urlencoded/spec/form-urlencoded.spec.js' {
  declare module.exports: $Exports<'form-urlencoded/spec/form-urlencoded.spec'>;
}
declare module 'form-urlencoded/spec/helpers/reporter.js' {
  declare module.exports: $Exports<'form-urlencoded/spec/helpers/reporter'>;
}
