// flow-typed signature: 4b57561da583badbb712eeb3ef95e0de
// flow-typed version: <<STUB>>/i18next-node-fs-backend_v^1.2.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-node-fs-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-node-fs-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-node-fs-backend/lib/index' {
  declare module.exports: any;
}

declare module 'i18next-node-fs-backend/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-node-fs-backend/index' {
  declare module.exports: $Exports<'i18next-node-fs-backend'>;
}
declare module 'i18next-node-fs-backend/index.js' {
  declare module.exports: $Exports<'i18next-node-fs-backend'>;
}
declare module 'i18next-node-fs-backend/lib/index.js' {
  declare module.exports: $Exports<'i18next-node-fs-backend/lib/index'>;
}
declare module 'i18next-node-fs-backend/lib/utils.js' {
  declare module.exports: $Exports<'i18next-node-fs-backend/lib/utils'>;
}
