// flow-typed signature: 3b6a60dfa730d72b964bd1c5391d7766
// flow-typed version: <<STUB>>/i18next-express-middleware_v^1.3.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'i18next-express-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'i18next-express-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'i18next-express-middleware/lib/index' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/LanguageDetector' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/languageLookups/cookie' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/languageLookups/header' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/languageLookups/path' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/languageLookups/querystring' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/languageLookups/session' {
  declare module.exports: any;
}

declare module 'i18next-express-middleware/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'i18next-express-middleware/lib/index.js' {
  declare module.exports: $Exports<'i18next-express-middleware/lib/index'>;
}
declare module 'i18next-express-middleware/lib/LanguageDetector.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/LanguageDetector',
  >;
}
declare module 'i18next-express-middleware/lib/languageLookups/cookie.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/languageLookups/cookie',
  >;
}
declare module 'i18next-express-middleware/lib/languageLookups/header.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/languageLookups/header',
  >;
}
declare module 'i18next-express-middleware/lib/languageLookups/path.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/languageLookups/path',
  >;
}
declare module 'i18next-express-middleware/lib/languageLookups/querystring.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/languageLookups/querystring',
  >;
}
declare module 'i18next-express-middleware/lib/languageLookups/session.js' {
  declare module.exports: $Exports<
    'i18next-express-middleware/lib/languageLookups/session',
  >;
}
declare module 'i18next-express-middleware/lib/utils.js' {
  declare module.exports: $Exports<'i18next-express-middleware/lib/utils'>;
}
