// flow-typed signature: 5b23a9fa67ebe03964915b5b530ea7b7
// flow-typed version: <<STUB>>/react-i18next_v^7.3.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-i18next'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-i18next' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-i18next/dist/amd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/amd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/I18n' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/commonjs/translate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/context' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/I18n' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/es/translate' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/dist/umd/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next' {
  declare module.exports: any;
}

declare module 'react-i18next/react-i18next.min' {
  declare module.exports: any;
}

declare module 'react-i18next/rollup.config' {
  declare module.exports: any;
}

declare module 'react-i18next/src/context' {
  declare module.exports: any;
}

declare module 'react-i18next/src/I18n' {
  declare module.exports: any;
}

declare module 'react-i18next/src/I18nextProvider' {
  declare module.exports: any;
}

declare module 'react-i18next/src/index' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Interpolate' {
  declare module.exports: any;
}

declare module 'react-i18next/src/loadNamespaces' {
  declare module.exports: any;
}

declare module 'react-i18next/src/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-i18next/src/Trans' {
  declare module.exports: any;
}

declare module 'react-i18next/src/translate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-i18next/dist/amd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next'>;
}
declare module 'react-i18next/dist/amd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/amd/react-i18next.min'>;
}
declare module 'react-i18next/dist/commonjs/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/context'>;
}
declare module 'react-i18next/dist/commonjs/I18n.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/I18n'>;
}
declare module 'react-i18next/dist/commonjs/I18nextProvider.js' {
  declare module.exports: $Exports<
    'react-i18next/dist/commonjs/I18nextProvider',
  >;
}
declare module 'react-i18next/dist/commonjs/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/index'>;
}
declare module 'react-i18next/dist/commonjs/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Interpolate'>;
}
declare module 'react-i18next/dist/commonjs/loadNamespaces.js' {
  declare module.exports: $Exports<
    'react-i18next/dist/commonjs/loadNamespaces',
  >;
}
declare module 'react-i18next/dist/commonjs/shallowEqual.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/shallowEqual'>;
}
declare module 'react-i18next/dist/commonjs/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/Trans'>;
}
declare module 'react-i18next/dist/commonjs/translate.js' {
  declare module.exports: $Exports<'react-i18next/dist/commonjs/translate'>;
}
declare module 'react-i18next/dist/es/context.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/context'>;
}
declare module 'react-i18next/dist/es/I18n.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/I18n'>;
}
declare module 'react-i18next/dist/es/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/I18nextProvider'>;
}
declare module 'react-i18next/dist/es/index.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/index'>;
}
declare module 'react-i18next/dist/es/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Interpolate'>;
}
declare module 'react-i18next/dist/es/loadNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/loadNamespaces'>;
}
declare module 'react-i18next/dist/es/shallowEqual.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/shallowEqual'>;
}
declare module 'react-i18next/dist/es/Trans.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/Trans'>;
}
declare module 'react-i18next/dist/es/translate.js' {
  declare module.exports: $Exports<'react-i18next/dist/es/translate'>;
}
declare module 'react-i18next/dist/umd/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next'>;
}
declare module 'react-i18next/dist/umd/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/dist/umd/react-i18next.min'>;
}
declare module 'react-i18next/react-i18next.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next'>;
}
declare module 'react-i18next/react-i18next.min.js' {
  declare module.exports: $Exports<'react-i18next/react-i18next.min'>;
}
declare module 'react-i18next/rollup.config.js' {
  declare module.exports: $Exports<'react-i18next/rollup.config'>;
}
declare module 'react-i18next/src/context.js' {
  declare module.exports: $Exports<'react-i18next/src/context'>;
}
declare module 'react-i18next/src/I18n.js' {
  declare module.exports: $Exports<'react-i18next/src/I18n'>;
}
declare module 'react-i18next/src/I18nextProvider.js' {
  declare module.exports: $Exports<'react-i18next/src/I18nextProvider'>;
}
declare module 'react-i18next/src/index.js' {
  declare module.exports: $Exports<'react-i18next/src/index'>;
}
declare module 'react-i18next/src/Interpolate.js' {
  declare module.exports: $Exports<'react-i18next/src/Interpolate'>;
}
declare module 'react-i18next/src/loadNamespaces.js' {
  declare module.exports: $Exports<'react-i18next/src/loadNamespaces'>;
}
declare module 'react-i18next/src/shallowEqual.js' {
  declare module.exports: $Exports<'react-i18next/src/shallowEqual'>;
}
declare module 'react-i18next/src/Trans.js' {
  declare module.exports: $Exports<'react-i18next/src/Trans'>;
}
declare module 'react-i18next/src/translate.js' {
  declare module.exports: $Exports<'react-i18next/src/translate'>;
}
