export type MeetupObject = {
  _id?: string,
  type?: string,
  note?: string,
  meetupAddress?: string,
  meetupLatitude?: number,
  meetupLongitude?: number,
  meetupSunday?: boolean,
  meetupMonday?: boolean,
  meetupTuesday?: boolean,
  meetupWednesday?: boolean,
  meetupThursday?: boolean,
  meetupFriday?: boolean,
  meetupSaturday?: boolean,
  meetupStartTime?: string,
  meetupEndTime?: string,
};
