export type MeetupObject = {
  _id?: string,
  type?: string,
  note?: string,
  meetupAddress?: string,
  meetupLatitude?: number,
  meetupLongitude?: number,
  meetupSunday?: boolean,
  meetupMonday?: boolean,
  meetupTuesday?: boolean,
  meetupWednesday?: boolean,
  meetupThursday?: boolean,
  meetupFriday?: boolean,
  meetupSaturday?: boolean,
  meetupStartTime?: string,
  meetupEndTime?: string,
};

export type MenuObject = {
  _id?: string,
  serving?: string,
  cookingBuffer?: string,
  description?: string,
  quantity?: number,
  unitPrice?: string,
  dishName?: string,
  email?: string,
  deliveryList?: Array<MeetupObject>,
  images?: Array<string>,
  ingredients?: Array<string>,
  category?: Array<string>,
};
